balances:
  - CDDT7HvMb2Y34gPJ2XvXdvj5VAirpBaqbENjnnx2Qazg
  - B3LfEJZSZHTuVzeyHBEyv2nYvvKLt2VGzYEyMjDJ7QD1
  - 6tnNqsutfN7cYiDEuCQiq8qSazzxzVccqstmtW16wDze
send_from:
  - test_1
  - test_2
send_to:
  - test_1
  - test_2
on_block_from: test
on_block_to: test
wallet_program: test